#!/usr/bin/env bash

set +e

if [ -f "$1" ]; then

  while true
  do
    echo "fpinging the targets..."
    fping -f $1
    sleep 2
    clear
  done

else

  echo "You must provide a valid filename with target IP address list."

fi
