---

###################################################
# Tenants and Per-VRF Config                      #
###################################################
tenants:
  - name: DOMAIN_A_FABRIC
    mac_vrf_vni_base: 10000
    evpn_l2_multi_domain: false
    vrfs:
      - name: PROD
        vrf_vni: 50001
        evpn_l3_multicast:
          enabled: true
          evpn_underlay_l3_multicast_group: 232.1.1.1
        mlag_ibgp_peering_vlan: 3001
        mlag_ibgp_peering_ipv4_pool: 192.2.2.0/31
        vtep_diagnostic:
          loopback: 101
          loopback_ip_range: 10.101.101.0/24
        svis:
          - id: 10
            name: Blue
            description: Blue Network
            tags: ['PROD', 'BLUE']
            enabled: true
            mtu: 9014
            ip_address_virtual: 10.10.10.1/24
            ipv6_address_virtuals: [2001:db8:10:10::1/64]
            evpn_l2_multi_domain: true
          - id: 30
            name: Orange
            description: Orange Network
            tags: ['PROD', 'ORANGE']
            enabled: true
            mtu: 9014
            ip_address_virtual: 10.30.30.1/24
            ipv6_address_virtuals: [2001:db8:30:30::1/64]
      - name: DEV
        vrf_vni: 50002
        evpn_l3_multicast:
          enabled: true
          evpn_underlay_l3_multicast_group: 232.2.2.2
        mlag_ibgp_peering_vlan: 3002
        mlag_ibgp_peering_ipv4_pool: 192.2.2.0/31
        vtep_diagnostic:
          loopback: 102
          loopback_ip_range: 10.102.102.0/24
        svis:
          - id: 50
            name: Yellow
            description: Yellow Network
            tags: ['DEV', 'YELLOW']
            enabled: true
            mtu: 9014
            ip_address_virtual: 10.50.50.1/24
            ipv6_address_virtuals: [2001:db8:50:50::1/64]
            evpn_l2_multi_domain: true
          - id: 70
            name: Brown
            description: Brown Network
            tags: ['DEV', 'BROWN']
            enabled: true
            mtu: 9014
            ip_address_virtual: 10.70.70.1/24
            ipv6_address_virtuals: [2001:db8:70:70::1/64]
            evpn_l2_multi_domain: true
