---

- name: Deploy Switch Configurations
  hosts: "{{ target_hosts }}"
  gather_facts: false

  tasks:

    - name: Deploy Configuration to Device
      ansible.builtin.import_role:
        name: arista.avd.eos_config_deploy_eapi
