---
- name: Run ANTA validation
  hosts: AVD_FABRIC
  connection: local
  gather_facts: false
  tasks:

    - name: Run ANTA on EOS devices
      ansible.builtin.import_role:
        name: arista.avd.anta_runner
