---

########################################################
# Port Profiles                                        #
########################################################
port_profiles:
  - profile: PROF-BLUE-MLAG
    mode: access
    spanning_tree_portfast: edge
    spanning_tree_bpduguard: true
    vlans: 10
    port_channel:
      mode: active

  - profile: PROF-ORANGE-MLAG
    mode: access
    spanning_tree_portfast: edge
    spanning_tree_bpduguard: true
    vlans: 30
    port_channel:
      mode: active

  - profile: PROF-ORANGE-SINGLE-HOMED
    mode: access
    spanning_tree_portfast: edge
    spanning_tree_bpduguard: true
    vlans: 30

  - profile: PROF-YELLOW-SINGLE-HOMED
    mode: access
    spanning_tree_portfast: edge
    spanning_tree_bpduguard: true
    vlans: 50

  - profile: PROF-BROWN-MLAG
    mode: access
    spanning_tree_portfast: edge
    spanning_tree_bpduguard: true
    vlans: 70
    port_channel:
      mode: active

########################################################
# End hosts                                            #
########################################################
servers:
  - name: HostA1
    adapters:
      - endpoint_ports: [eth1, eth2]
        switch_ports: [Ethernet7, Ethernet7]
        switches: [A-LEAF1, A-LEAF2]
        profile: PROF-BLUE-MLAG

  - name: HostA2
    adapters:
      - endpoint_ports: [eth1, eth2]
        switch_ports: [Ethernet8, Ethernet8]
        switches: [A-LEAF1, A-LEAF2]
        profile: PROF-ORANGE-MLAG

  - name: HostA3
    adapters:
      - endpoint_ports: [eth1]
        switch_ports: [Ethernet7]
        switches: [A-LEAF3]
        profile: PROF-YELLOW-SINGLE-HOMED

  - name: HostA4
    adapters:
      - endpoint_ports: [eth1, eth2]
        switch_ports: [Ethernet8, Ethernet8]
        switches: [A-LEAF3, A-LEAF4]
        profile: PROF-BLUE-MLAG

  - name: HostA5
    adapters:
      - endpoint_ports: [eth1]
        switch_ports: [Ethernet7]
        switches: [A-LEAF4]
        profile: PROF-ORANGE-SINGLE-HOMED

  - name: HostA6
    adapters:
      - endpoint_ports: [eth1, eth2]
        switch_ports: [Ethernet7, Ethernet7]
        switches: [A-LEAF5, A-LEAF6]
        profile: PROF-BROWN-MLAG
