---

- name: Validate Fabric
  hosts: "{{ target_hosts }}"
  gather_facts: false

  tasks:
    - name: Validate Fabric
      ansible.builtin.import_role:
        name: arista.avd.eos_validate_state
      vars:
        save_catalog: true
