---
###################################################
# B-LEAF8 — EVPN Gateway (All-Active), Domain B
###################################################

evpn_multicast: false
underlay_multicast_pim_sm: false

b_leaf8_gateway_csc:
  router_bgp:
    neighbors:
      - ip_address: 172.16.2.2
        peer_group: REMOTE-IPV4-PEERS
        description: BB1.IPV4
      - ip_address: 172.16.2.6
        peer_group: REMOTE-IPV4-PEERS
        description: BB2.IPV4
    peer_groups:
      - name: LOCAL-EVPN-PEERS
        session_tracker: TRACK-LOCAL-EVPN-PEERS
    eos_cli: |
      !
      address-family evpn
         route type ethernet-segment route-target auto
         domain identifier 65208:65208 attach
    session_trackers:
      - name: TRACK-LOCAL-EVPN-PEERS
        recovery_delay: 10
    # Multi-domain MAC-VRFs on VLANs 10 and 70.
    vlans:
      - id: 10
        rd_evpn_domain:
          domain: all
          rd: '10.0.2.8:10010'
        route_targets:
          import_export_evpn_domains:
            - domain: all
              route_target: '10010:10010'
      - id: 70
        rd_evpn_domain:
          domain: all
          rd: '10.0.2.8:10070'
        route_targets:
          import_export_evpn_domains:
            - domain: all
              route_target: '10070:10070'
    vrfs:
      - name: PROD
        rd_evpn_domain:
          domain: all
          rd: '10.0.2.8:50001'
        route_targets:
          import_evpn_domains:
            - domain: all
              route_target: '50001:50001'
          export_evpn_domains:
            - domain: all
              route_target: '50001:50001'
      - name: DEV
        rd_evpn_domain:
          domain: all
          rd: '10.0.2.8:50002'
        route_targets:
          import_evpn_domains:
            - domain: all
              route_target: '50002:50002'
          export_evpn_domains:
            - domain: all
              route_target: '50002:50002'

b_leaf8_hostb8_csc:
  port_channel_interfaces:
    - name: Port-Channel9
      bgp:
        session_tracker: TRACK-LOCAL-EVPN-PEERS

custom_structured_configuration_router_bgp: "{{ b_leaf8_gateway_csc.router_bgp }}"
custom_structured_configuration_port_channel_interfaces: "{{ b_leaf8_hostb8_csc.port_channel_interfaces }}"
