---
###################################################
# B-LEAF8 — EVPN Gateway (All-Active), Domain B
###################################################

evpn_multicast: false
underlay_multicast: false

b_leaf8_gateway_csc:
  router_bgp:
    neighbors:
      - ip_address: 172.16.2.2
        peer_group: REMOTE-IPV4-PEERS
        description: BB1.IPV4
      - ip_address: 172.16.2.6
        peer_group: REMOTE-IPV4-PEERS
        description: BB2.IPV4
    peer_groups:
      - name: LOCAL-EVPN-PEERS
        session_tracker: TRACK-LOCAL-EVPN-PEERS
    address_family_evpn:
      route:
        - type: ethernet-segment
          route_target: auto
      domain_identifier_attach: '65208:65208'
    session_trackers:
      - name: TRACK-LOCAL-EVPN-PEERS
        recovery_delay: 10

b_leaf8_hostb8_csc:
  port_channel_interfaces:
    - name: Port-Channel9
      bgp:
        session_tracker: TRACK-LOCAL-EVPN-PEERS

structured_config:
  router_bgp: "{{ b_leaf8_gateway_csc.router_bgp }}"
  port_channel_interfaces: "{{ b_leaf8_hostb8_csc.port_channel_interfaces }}"
