---

l3_edge:
  p2p_links_profiles:
    - name: DCI
      mtu: 9214
      include_in_underlay_protocol: false

  p2p_links:
    - nodes: [A-LEAF7, BB1]
      interfaces: [Ethernet7, Ethernet1]
      ip: [172.16.1.1/31, 172.16.1.0/31]
      profile: DCI
    - nodes: [A-LEAF8, BB1]
      interfaces: [Ethernet7, Ethernet2]
      ip: [172.16.1.3/31, 172.16.1.2/31]
      profile: DCI
    - nodes: [A-LEAF7, BB2]
      interfaces: [Ethernet8, Ethernet1]
      ip: [172.16.1.5/31, 172.16.1.4/31]
      profile: DCI
    - nodes: [A-LEAF8, BB2]
      interfaces: [Ethernet8, Ethernet2]
      ip: [172.16.1.7/31, 172.16.1.6/31]
      profile: DCI

    - nodes: [B-LEAF7, BB1]
      interfaces: [Ethernet7, Ethernet3]
      ip: [172.16.2.1/31, 172.16.2.0/31]
      profile: DCI
    - nodes: [B-LEAF8, BB1]
      interfaces: [Ethernet7, Ethernet4]
      ip: [172.16.2.3/31, 172.16.2.2/31]
      profile: DCI
    - nodes: [B-LEAF7, BB2]
      interfaces: [Ethernet8, Ethernet3]
      ip: [172.16.2.5/31, 172.16.2.4/31]
      profile: DCI
    - nodes: [B-LEAF8, BB2]
      interfaces: [Ethernet8, Ethernet4]
      ip: [172.16.2.7/31, 172.16.2.6/31]
      profile: DCI

    - nodes: [BB1, BB2]
      interfaces: [Ethernet5, Ethernet5]
      ip: [172.16.255.0/31, 172.16.255.1/31]
      profile: DCI
