---
tenants:
  - name: FABRIC_B
    mac_vrf_vni_base: 10000
    vrfs:
      - name: default
        svis:
          - id: 10
            name: 'TEN'
            enabled: true
            ip_virtual_router_addresses:
              - 10.10.10.1
            structured_config:
              ospf_area: 0.0.0.0
            nodes:
              - node: B-SPINE1
                ip_address: 10.10.10.4/24
              - node: B-SPINE2
                ip_address: 10.10.10.5/24
          - id: 20
            name: 'TWENTY'
            enabled: true
            ip_virtual_router_addresses:
              - 10.20.20.1
            structured_config:
              ospf_area: 0.0.0.0
            nodes:
              - node: B-SPINE1
                ip_address: 10.20.20.4/24
              - node: B-SPINE2
                ip_address: 10.20.20.5/24
          - id: 40
            name: 'Forty'
            enabled: true
            ip_virtual_router_addresses:
              - 10.40.40.1
            structured_config:
              ospf_area: 0.0.0.0
            nodes:
              - node: B-SPINE1
                ip_address: 10.40.40.4/24
              - node: B-SPINE2
                ip_address: 10.40.40.5/24
