{
 "title": "Connectivity Monitor",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Device", "query": { "query": "label_values(source)" } }
  ]
 },
 "panels": [
  {
   "title": "Connectivity Monitor Hosts",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "gnmic_conn_mon_packet_loss{source=\"$Device\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gnmic_conn_mon_url{source=\"$Device\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gnmic_conn_mon_latency{source=\"$Device\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gnmic_conn_mon_jitter{source=\"$Device\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gnmic_conn_mon_http_response_time{source=\"$Device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "gnmic_conn_mon_http_response_time{source=\"$Device\"}",
     "legendFormat": "{{host_status_host_name}} ({{http_stats_url}})"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "gnmic_conn_mon_jitter{source=\"$Device\"}",
     "legendFormat": "{{host_status_host_name}} ({{icmp_stats_ip_addr}})"
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gnmic_conn_mon_packet_loss{source=\"$Device\"}",
     "legendFormat": "{{host_status_host_name}} ({{icmp_stats_ip_addr}})"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "gnmic_conn_mon_latency{source=\"$Device\"}",
     "legendFormat": "{{host_status_host_name}} ({{icmp_stats_ip_addr}})"
    }
   ]
  }
 ]
}