{
 "title": "Connectivity Monitor - Global",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Connectivity Monitor Hosts",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(label_join(gnmic_conn_mon_packet_loss, \"description\", \"~\", \"source\", \"host_status_vrf_name\", \"icmp_stats_interface_name\", \"host_status_host_name\"), \"description\", \"$1 ($2 / $3) to $4\", \"description\", \"([^~]+)~([^~]+)~([^~]+)~([^~]+)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(label_join(gnmic_conn_mon_url, \"description\", \"~\", \"source\", \"host_status_vrf_name\", \"http_stats_interface_name\", \"host_status_host_name\"), \"description\", \"$1 ($2 / $3) to $4\", \"description\", \"([^~]+)~([^~]+)~([^~]+)~([^~]+)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(label_join(gnmic_conn_mon_latency, \"description\", \"~\", \"source\", \"host_status_vrf_name\", \"icmp_stats_interface_name\", \"host_status_host_name\"), \"description\", \"$1 ($2 / $3) to $4\", \"description\", \"([^~]+)~([^~]+)~([^~]+)~([^~]+)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(label_join(gnmic_conn_mon_jitter, \"description\", \"~\", \"source\", \"host_status_vrf_name\", \"icmp_stats_interface_name\", \"host_status_host_name\"), \"description\", \"$1 ($2 / $3) to $4\", \"description\", \"([^~]+)~([^~]+)~([^~]+)~([^~]+)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(label_join(gnmic_conn_mon_http_response_time, \"description\", \"~\", \"source\", \"host_status_vrf_name\", \"http_stats_interface_name\", \"host_status_host_name\"), \"description\", \"$1 ($2 / $3) to $4\", \"description\", \"([^~]+)~([^~]+)~([^~]+)~([^~]+)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "gnmic_conn_mon_http_response_time",
     "legendFormat": "{{source}} / {{host_status_host_name}} ({{http_stats_url}})"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "gnmic_conn_mon_jitter",
     "legendFormat": "{{source}} / {{host_status_host_name}} ({{icmp_stats_ip_addr}})"
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gnmic_conn_mon_packet_loss",
     "legendFormat": "{{source}} / {{host_status_host_name}} ({{icmp_stats_ip_addr}})"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "gnmic_conn_mon_latency",
     "legendFormat": "{{source}} / {{host_status_host_name}} ({{icmp_stats_ip_addr}})"
    }
   ]
  }
 ]
}