---
aaa_settings:
  local_users:
    - name: admin
      privilege: 15
      role: network-admin
      no_password: true
    - name: arista
      privilege: 15
      role: network-admin
      sha512_password: "$6$7t1sx38LSYabjfkz$TNsa1HyVX4kehVvqFvJVF1omlYKxUkeAV4AfDlJ3tQnSoR1GfaaaicGyKjVJG/s63wxiTW1zgbchOH2dZ38lH."
custom_structured_configuration_aaa_authorization:
    exec:
      default: local

dns_settings:
  servers:
    - ip_address: 1.1.1.1
      vrf: MGMT
    - ip_address: 8.8.8.8
      vrf: MGMT

ntp_settings:
  server_vrf: MGMT
  servers:
  - name: time.google.com

custom_structured_configuration_spanning_tree:
  mode: mstp

# hardcoding management0 for cEOS lab compatibility (default: Management1)
mgmt_interface: Management0
mgmt_gateway: 172.144.100.1
mgmt_interface_vrf: MGMT

# Management eAPI | Required for this Lab
custom_structured_configuration_management_api_http:
  https_ssl_profile: eAPI

# Management security required for SSL profile with strong ciphers
custom_structured_configuration_management_security:
  ssl_profiles:
    - name: eAPI
      certificate:
        file: eAPI.crt
        key: eAPI.key
      cipher_list: 'HIGH:!eNULL:!aNULL:!MD5:!ADH:!ANULL'

# Management GNMI | Optional
custom_structured_configuration_management_api_gnmi:
  provider: "eos-native"
  transport:
    grpc:
    - name: MGMT
      vrf: MGMT
      notification_timestamp: "send-time"
    - name: default
      notification_timestamp: "send-time"


custom_structured_configuration_monitor_connectivity:
  shutdown: false
  interval: 5
  vrfs:
    - name: MGMT
      interface_sets:
        - name: MyIntfSet
          interfaces: Management0
      local_interfaces: MyIntfSet
      hosts:
        - name: google
          ip: 8.8.8.8
          local_interfaces: MyIntfSet
          url: https://www.google.com
        - name: cloudflare
          ip: 1.1.1.1
          local_interfaces: MyIntfSet
          url: https://cloudflare.com
        - name: aristaio
          ip: 172.66.1.251
          url: https://www.arista.io
        - name: aristacom
          ip: 199.232.26.132
          url: https://www.arista.com
