all:
  children:
    AVD_LAB:
      children:
        OM_FABRIC:
          children:
            OM_SPINES:
              hosts:
                spine1:
                  ansible_host: 172.144.100.2
                spine2:
                  ansible_host: 172.144.100.3
            OM_PES:
              hosts:
                pe11:
                  ansible_host: 172.144.100.4
                pe12:
                  ansible_host: 172.144.100.5
                pe21:
                  ansible_host: 172.144.100.6
                pe22:
                  ansible_host: 172.144.100.7

          vars:
            ansible_connection: httpapi
            ansible_httpapi_use_ssl: true
            ansible_httpapi_validate_certs: false
            ansible_user: arista
            ansible_password: arista
            ansible_become: true
            ansible_become_method: enable
            ansible_network_os: eos
            ansible_httpapi_port: 443
            ansible_python_interpreter: $(which python3)
        OM_NETWORK_SERVICES:
          children:
            OM_PES:

        OM_CONNECTED_ENDPOINTS:
          children:
            OM_PES:
