---
name: Create aristalabs container images

on:
  push:
    branches: ['**']  # branches will be filtered in the jobs
    paths:
      - .github/workflows/container_build_child.yml
      - .github/workflows/container_build_parent_matrix.yml
      - containers/lab-base/**
  workflow_dispatch:
    branches: ['**']  # branches will be filtered in the jobs

permissions:
  packages: write

jobs:
  build-lab-containers:
    # fork - build container from any branch for testing
    # parent repo - build on main branch only
    if: github.repository != 'aristanetworks/acLabs' || github.ref == 'refs/heads/main'
    uses: ./.github/workflows/container_build_child.yml
    strategy:
      matrix:
        from_image: ["ghcr.io/aristanetworks/avd/universal"]
        from_variant: ["python3.11-avd-v5.7.0"]
        clab_version: ["0.69.3"]
    with:
      container_name: "aristalabs"
      from_image: ${{ matrix.from_image }}
      from_variant: ${{ matrix.from_variant }}
      clab_version: ${{ matrix.clab_version }}
      container_revision: "0.1"
